[BallModel]
AccSlideMmS2=-2750
AccRollMmS2=-100
KSwitch=0.7
DirectKickNormalRestitution=0.8
DirectKickTangentRetention=1.0

[Camera]
HideBallMode=false
OnboardFrameHeight=480
OnboardFrameWidth=640

[Diag]
RobotCsvPath=
RobotId=-1

[Display]
ForceDebugDrawMode=false
NumThreads=4
height=847
width=1212

[Encoder]
BiasMps=0.0
Enabled=true
FeedbackAddress=224.5.69.4
FeedbackPort=16941
NoiseSigmaMps=0.0
QuantizationMps=0.0
RobotRadiusMm=90.0
Team=blue
WheelAngleBlDeg=135.0
WheelAngleBrDeg=-135.0
WheelAngleFlDeg=60.0
WheelAngleFrDeg=-60.0
WheelRadiusMm=26.0

[Geometery]
FieldLength=15400
FieldWidth=12400
GoalDepth=1800
GoalWidth=3600
LineThickness=50
PenaltyAreaDepth=3000
PenaltyAreaWidth=6000
RadiusCenterCircle=3000
RadiusCornerArc=500
RadiusPenaltyArc=1000

[LightMode]
BlueRobot=false
Field=false
Stadium=false
YellowRobot=false

[Network]
blueTeamControlPort=10301
commandListenPort=20694
visionMulticastAddress=224.5.23.2
visionMulticastPort=10694
yellowTeamControlPort=10302

[Physics]
AccBrakeAbsoluteMax=5000
AccBrakeAngularMax=100
AccSpeedupAbsoluteMax=5000
AccSpeedupAngularMax=100
BallRestitution=0.8
CCD=true
DesiredFps=60
Gravity=9.8
KickerFriction=0.99
MaxChipKickSpeed=10
MaxLinearKickSpeed=10
VelAbsoluteMax=5000
VelAngularMax=20

[Robot]
blueRobotCount=11
yellowRobotCount=11

[RobotModel]
Enabled=true
MaxAngularAccelRadS2=35

[RobotModel.0]
; ID0: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.1]
; ID1: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.2]
; ID2: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.3]
; ID3: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.4]
; ID4: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.5]
; ID5: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.6]
; ID6: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.7]
; ID7: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.8]
; ID8: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.9]
; ID9: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.10]
; ID10: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.11]
; ID11: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.12]
; ID12: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.13]
; ID13: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.14]
; ID14: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35

[RobotModel.15]
; ID15: RAVEN ID2 (ID2 (d83add4cb8bd)) の同一モデル
TauVxSec=0.0432603552
TauVySec=0.0513616437
TauOmegaSec=0.0385279851
DeadTimeSec=0.087
TractionAccelXMmS2=4269
TractionAccelYMmS2=3740
TractionDecelXMmS2=6000
TractionDecelYMmS2=6000
GainVx=0.88
GainVy=0.83
GainVyFromUx=-0.036
GainVxFromUy=-0.028
GainOmega=0.937
WheelRimSpeedBudgetMmS=2250
MaxAngularVelRadS=8.42
MaxAngularAccelRadS2=35
